package:
    name: trmm_rsl
    version: 1.49

source:
    fn: rsl.v1.49.tar.gz
    url: ftp://trmm-fc.gsfc.nasa.gov/software/rsl-v1.49.tar.gz

build:
    number: 0

about:
    home: http://trmm-fc.gsfc.nasa.gov/trmm_gv/software/rsl/ 
    license: LGPL
